### ISSUE TITLE
i have issue with , when i opne the app its close automatic what can i do for it

### ISSUE THREAD

**Issue by surajsingh8979** [surajsingh8979/chatting#1]

**Comment by surajsingh8979** [comment]
2021-02-20 19:04:38.273 23626-23626/com.example.chatting e/androidruntime: fatal exception: main process: com.example.chatting, pid: 23626 java.lang.nullpointerexception: attempt to invoke virtual method 'boolean java.lang.string.equals(java.lang.object)' on a null object reference at com.example.chatting.fragments.chatfragment$1.ondatachange(chatfragment.java:62) at com.google.firebase.database.core.valueeventregistration.fireevent(valueeventregistration.java:75) at com.google.firebase.database.core.view.dataevent.fire(dataevent.java:63) at com.google.firebase.database.core.view.eventraiser$1.run(eventraiser.java:55) at android.os.handler.handlecallback(handler.java:883) at android.os.handler.dispatchmessage(handler.java:100) at android.os.looper.loop(looper.java:237) at android.app.activitythread.main(activitythread.java:7811) at java.lang.reflect.method.invoke(native method) at com.android.internal.os.runtimeinit$methodandargscaller.run(runtimeinit.java:493) at com.android.internal.os.zygoteinit.main(zygoteinit.java:1068)
